from discriminator import Discriminator
from discriminator import DomainConfusionVelocityDiscriminator
from discriminator import ConvDiscriminator
from discriminator import MLPDiscriminator
from discriminator import VelocityDiscriminator
from discriminator import DomainConfusionDiscriminator
